from enum import Enum, IntEnum


class MakerTaker(str, Enum):
    UNKNOWN = "Unknown"
    MAKER = "Maker"
    TAKER = "Taker"


class TimeInForce(IntEnum):
    GTC = 1
    OPG = 2
    IOC = 3
    FOK = 4
    GTX = 5
    GTD = 6


class Side(IntEnum):
    BUY = 0
    SELL = 1
    SHORT = 2
    UNKNOWN = 3


class OrderType(IntEnum):
    MARKET = 1
    LIMIT = 2
    STOP_MARKET = 3
    STOP_LIMIT = 4
    TRAILING_STOP_MARKET = 5
    TRAILING_STOP_LIMIT = 6
    BLOCK_TRADE = 7


class PegPriceType(IntEnum):
    LAST = 1
    BID = 2
    ASK = 3


class InstrumentState(str, Enum):
    BOTH = "Both"
    INACTIVE = "Inactive"


class ReportFrequency(str, Enum):
    ON_DEMAND = "onDemand"
    HOURLY = "Hourly"
    DAILY = "Daily"
    WEEKLY = "Weekly"
    MONTHLY = "Monthly"
    ANNUALLY = "Annually"


class ReportResultStatus(str, Enum):
    NOT_STARTED = "NotStarted"
    NOT_COMPLETE = "NotComplete"
    ERROR_COMPLETE = "ErrorComplete"
    SUCCESS_COMPLETE = "SuccessComplete"
    CANCELLED = "Cancelled"


class ReportRequestStatus(str, Enum):
    SUBMITTED = "Submitted"
    VALIDATING = "Validating"
    SCHEDULED = "Scheduled"
    IN_PROGRESS = "InProgress"
    COMPLETED = "Completed"
    ABORTING = "Aborting"
    ABORTED = "Aborted"
    USER_CANCELLED = "UserCancelled"
    SYS_RETIRED = "SysRetired"
    USER_CANCELLED_PENDING = "UserCancelledPending"


class BankAccountKind(str, Enum):
    CORRIENTE = "corriente"
    VISTA = "vista"
    AHORRO = "ahorro"
    ELECTRONIC_CHECKBOOK = "electronic_checkbook"
    AR_CBU = "ar_cbu"
    AR_CVU = "ar_cvu"
    AR_ALIAS = "ar_alias "
    BR_CORRIENTE_FISICA = "br_corriente_fisica"
    BR_SIMPLE_FISICA = "br_simple_fisica"
    BR_CORRIENTE_JURIDICA = "br_corriente_juridica"
    BR_POUPANCA_FISICA = "br_poupanca_fisica"
    BR_POUPANCA_JURIDICA = "br_poupanca_juridica"
    BR_CAIXA_FACIL = "br_caixa_facil"
    BR_PIX = "br_pix"


class PixType(str, Enum):
    CPF = "CPF"
    CNPJ = "CNPJ"
    EMAIL = "Email"
    PHONE = "Phone"
    OTRO = "Otro"


class UpdateOneStepWithdrawAction(str, Enum):
    ENABLE = "enable"
    DISABLE = "disable"


class DepositPaymentMethod(IntEnum):
    BANK_TRANSFER = 1
    WEB_PAY = 2


class QuoteMode(str, Enum):
    DIRECT = "direct"
    INVERSE = "inverse"


class QuoteOperation(IntEnum):
    BUY = 1
    SELL = 2
    CONVERSION = 3


class Gender(IntEnum):
    WOMAN = 0
    MAN = 1


class IdentityType(IntEnum):
    DNI = 1
    EXTRANJERO = 2
    NUIP = 3
    NIP = 4
    PEP = 5
    CC = 6
    CE = 7
    PASAPORTE = 8


class Profession(str, Enum):
    TRADER = "trader"
    INVESTOR = "investor"
    STUDENT = "student"
    HOUSEWIFE = "housewife"
    ACCOUNTANT = "accountant"
    ACTOR_ACTRESS = "actor_actress"
    AIR_HOSTESS = "air_hostess"
    ARCHAEOLOGIST = "archaeologist"
    ARCHITECT = "architect"
    ASTRONAUT = "astronaut"
    BAKER = "baker"
    BIOLOGIST = "biologist"
    BRICKLAYER = "bricklayer"
    DRIVER = "driver"
    BUSINESSMAN = "businessman"
    BUTCHER = "butcher"
    CARETAKER_JANITOR_PORTER = "caretaker_janitor_porter"
    CARPENTER = "carpenter"
    CASHIER = "cashier"
    CLEANER = "cleaner"
    CLOWN = "clown"
    COBBLER = "cobbler"
    COOK_CHEF = "cook_chef"
    CHEMIST = "chemist"
    DANCER = "dancer"
    DECORATOR = "decorator"
    DENTIST = "dentist"
    DESIGNER = "designer"
    PHYSICIAN = "physician"
    DRESSMAKER = "dressmaker"
    DUSTMAN = "dustman"
    ECONOMIST = "economist"
    ELECTRICIAN = "electrician"
    ENGINEER = "engineer"
    FARMER = "farmer"
    FIREMAN = "fireman"
    FISHERMAN = "fisherman"
    FLORIST = "florist"
    FRUITERER = "fruiterer"
    GARDENER = "gardener"
    GEOLOGIST = "geologist"
    HAIRDRESSER = "hairdresser"
    JEWELLER = "jeweller"
    JOURNALIST = "journalist"
    JUDGE = "judge"
    LAWYER = "lawyer"
    LIBRARIAN = "librarian"
    LIFE_GUARD = "life_guard"
    MAILMAN_POSTMAN = "mailman_postman"
    MECHANIC = "mechanic"
    METEOROLOGIST = "meteorologist"
    CRYPTOCURRENCY_MINER = "cryptocurrency_miner"
    MINERAL_MINER = "mineral_miner"
    MODEL = "model"
    NANNY_NURSEMAID = "nanny_nursemaid"
    NUN = "nun"
    NURSE = "nurse"
    PAINTER = "painter"
    PASTRY_COOK = "pastry_cook"
    PHARMACIST = "pharmacist"
    PHOTOGRAPHER = "photographer"
    PHYSICIST = "physicist"
    PLUMBER = "plumber"
    POLICEMAN_POLICEWOMAN = "policeman_policewoman"
    POLITICIAN = "politician"
    PRIEST = "priest"
    PROFESSOR_TEACHER = "professor_teacher"
    PROGRAMMER = "programmer"
    PSYCHIATRIST = "psychiatrist"
    PSYCHOLOGIST = "psychologist"
    RECEPTIONIST = "receptionist"
    RESEARCHER_SCIENTIST = "researcher_scientist"
    SAILOR = "sailor"
    SALESMAN = "salesman"
    SECRETARY = "secretary"
    SHOP_ASSISTANT = "shop_assistant"
    SINGER = "singer"
    SOCIAL_WORKER = "social_worker"
    SPORTSMAN = "sportsman"
    SURGEON = "surgeon"
    TAXI_DRIVER = "taxi_driver"
    TELEPHONE_OPERATOR = "telephone_operator"
    TRAVEL_AGENT = "travel_agent"
    VETERINARIAN = "veterinarian"
    WAITER_WAITRESS = "waiter_waitress"
    WRITER = "writer"
    DELIVERYMAN = "deliveryman"
    UBER_DRIVER = "uber_driver"
    PILOT = "pilot"
    ADMINISTRATIVE = "administrative"
    PUBLIC_SERVANT = "public_servant"
    OTHER = "other"
    CUSTOMER_CARE = "customer_care"
    MILITARY = "military"
    MANAGER_OFFICIER = "manager_officier"


class CivilStatus(str, Enum):
    SOLTERO = "soltero"
    CASADO = "casado"
    CONVIVIENTE = "conviviente"
    DIVORCIADO = "divorciado"
    VIUDO = "viudo"


class ArProvince(IntEnum):
    BUENOS_AIRES = 1
    SANTA_FE = 2
    CORDOBA = 3
    MENDOZA = 4
    ENTRE_RIOS = 5
    SANTIAGO_DEL_ESTERO = 6
    SAN_JUAN = 7
    SAN_LUIS = 8
    LA_RIOJA = 9
    CATAMARCA = 10
    JUJUY = 11
    SALTA = 12
    FORMOSA = 13
    CHACO = 14
    CORRIENTES = 15
    MISIONES = 16
    TUCUMAN = 17
    LA_PAMPA = 18
    NEUQUEN = 19
    CHUBUT = 20
    RIO_NEGRO = 21
    SANTA_CRUZ = 22
    TIERRA_DEL_FUEGO = 23
    CIUDAD_AUTONOMA_DE_BUENOS_AIRES = 43


class BrState(str, Enum):
    RONDONIA = "RO"
    ACRE = "AC"
    AMAZONAS = "AM"
    RORAIMA = "RR"
    PARA = "PA"
    AMAPA = "AP"
    TOCANTINS = "TO"
    MARANHAO = "MA"
    PIAUI = "PI"
    CEARA = "CE"
    RIO_GRANDE_DO_NORTE = "RN"
    PARAIBA = "PB"
    PERNAMBUCO = "PE"
    ALAGOAS = "AL"
    SERGIPE = "SE"
    BAHIA = "BA"
    MINAS_GERAIS = "MG"
    ESPIRITO_SANTO = "ES"
    RIO_DE_JANEIRO = "RJ"
    SAO_PAULO = "SP"
    PARANA = "PR"
    SANTA_CATARINA = "SC"
    RIO_GRANDE_DO_SUL = "RS"
    MATO_GROSSO_DO_SUL = "MS"
    MATO_GROSSO = "MT"
    GOIAS = "GO"
    DISTRITO_FEDERAL = "DF"


class ChileanCommune(str, Enum):
    ARICA = "Arica"
    CAMARONES = "Camarones"
    GENERAL_LAGOS = "General Lagos"
    PUTRE = "Putre"
    ALTO_HOSPICIO = "Alto Hospicio"
    CAMINA = "Camiña"
    COLCHANE = "Colchane"
    HUARA = "Huara"
    IQUIQUE = "Iquique"
    PICA = "Pica"
    POZO_ALMONTE = "Pozo Almonte"
    ANTOFAGASTA = "Antofagasta"
    CALAMA = "Calama"
    MARIA_ELENA = "María Elena"
    MEJILLONES = "Mejillones"
    OLLAGUE = "Ollagüe"
    SAN_PEDRO_DE_ATACAMA = "San Pedro de Atacama"
    SIERRA_GORDA = "Sierra Gorda"
    TALTAL = "Taltal"
    TOCOPILLA = "Tocopilla"
    ALTO_DEL_CARMEN = "Alto del Carmen"
    CALDERA = "Caldera"
    CHANERAL = "Chañaral"
    COPIAPO = "Copiapó"
    DIEGO_DE_ALMAGRO = "Diego de Almagro"
    FREIRINA = "Freirina"
    HUASCO = "Huasco"
    TIERRA_AMARILLA = "Tierra Amarilla"
    VALLENAR = "Vallenar"
    ANDACOLLO = "Andacollo"
    CANELA = "Canela"
    COMBARBALA = "Combarbalá"
    COQUIMBO = "Coquimbo"
    ILLAPEL = "Illapel"
    LA_HIGUERA = "La Higuera"
    LA_SERENA = "La Serena"
    LOS_VILOS = "Los Vilos"
    MONTE_PATRIA = "Monte Patria"
    OVALLE = "Ovalle"
    PAIGUANO = "Paiguano"
    PUNITAQUI = "Punitaqui"
    RIO_HURTADO = "Río Hurtado"
    SALAMANCA = "Salamanca"
    VICUNA = "Vicuña"
    ALGARROBO = "Algarrobo"
    CABILDO = "Cabildo"
    CALERA = "Calera"
    CALLE_LARGA = "Calle Larga"
    CARTAGENA = "Cartagena"
    CASABLANCA = "Casablanca"
    CATEMU = "Catemu"
    CONCON = "Concón"
    EL_QUISCO = "El Quisco"
    EL_TABO = "El Tabo"
    HIJUELAS = "Hijuelas"
    ISLA_DE_PASCUA = "Isla de Pascua"
    JUAN_FERNANDEZ = "Juan Fernández"
    LA_CRUZ = "La Cruz"
    LA_LIGUA = "La Ligua"
    LIMACHE = "Limache"
    LLAILLAY = "Llaillay"
    LOS_ANDES = "Los Andes"
    NOGALES = "Nogales"
    OLMUE = "Olmué"
    PANQUEHUE = "Panquehue"
    PAPUDO = "Papudo"
    PETORCA = "Petorca"
    PUCHUNCAVI = "Puchuncaví"
    PUTAENDO = "Putaendo"
    QUILLOTA = "Quillota"
    QUILPUE = "Quilpué"
    QUINTERO = "Quintero"
    RINCONADA = "Rinconada"
    SAN_ANTONIO = "San Antonio"
    SAN_ESTEBAN = "San Esteban"
    SAN_FELIPE = "San Felipe"
    SANTA_MARIA = "Santa María"
    SANTO_DOMINGO = "Santo Domingo"
    VALPARAISO = "Valparaíso"
    VILLA_ALEMANA = "Villa Alemana"
    VINA_DEL_MAR = "Viña del Mar"
    ZAPALLAR = "Zapallar"
    ALHUE = "Alhué"
    BUIN = "Buin"
    CALERA_DE_TANGO = "Calera de Tango"
    CERRILLOS = "Cerrillos"
    CERRO_NAVIA = "Cerro Navia"
    COLINA = "Colina"
    CONCHALI = "Conchalí"
    CURACAVI = "Curacaví"
    EL_BOSQUE = "El Bosque"
    EL_MONTE = "El Monte"
    ESTACION_CENTRAL = "Estación Central"
    HUECHURABA = "Huechuraba"
    INDEPENDENCIA = "Independencia"
    ISLA_DE_MAIPO = "Isla de Maipo"
    LA_CISTERNA = "La Cisterna"
    LA_FLORIDA = "La Florida"
    LA_GRANJA = "La Granja"
    LA_PINTANA = "La Pintana"
    LA_REINA = "La Reina"
    LAMPA = "Lampa"
    LAS_CONDES = "Las Condes"
    LO_BARNECHEA = "Lo Barnechea"
    LO_ESPEJO = "Lo Espejo"
    LO_PRADO = "Lo Prado"
    MACUL = "Macul"
    MAIPU = "Maipú"
    MARIA_PINTO = "María Pinto"
    MELIPILLA = "Melipilla"
    NUNOA = "Ñuñoa"
    PADRE_HURTADO = "Padre Hurtado"
    PAINE = "Paine"
    PEDRO_AGUIRRE_CERDA = "Pedro Aguirre Cerda"
    PENAFLOR = "Peñaflor"
    PENALOLEN = "Peñalolén"
    PIRQUE = "Pirque"
    PROVIDENCIA = "Providencia"
    PUDAHUEL = "Pudahuel"
    PUENTE_ALTO = "Puente Alto"
    QUILICURA = "Quilicura"
    QUINTA_NORMAL = "Quinta Normal"
    RECOLETA = "Recoleta"
    RENCA = "Renca"
    SAN_BERNARDO = "San Bernardo"
    SAN_JOAQUIN = "San Joaquín"
    SAN_JOSE_DE_MAIPO = "San José de Maipo"
    SAN_MIGUEL = "San Miguel"
    SAN_PEDRO = "San Pedro"
    SAN_RAMON = "San Ramón"
    SANTIAGO = "Santiago"
    TALAGANTE = "Talagante"
    TILTIL = "Tiltil"
    VITACURA = "Vitacura"
    CHIMBARONGO = "Chimbarongo"
    CHEPICA = "Chépica"
    CODEGUA = "Codegua"
    COINCO = "Coinco"
    COLTAUCO = "Coltauco"
    DONIHUE = "Doñihue"
    GRANEROS = "Graneros"
    LA_ESTRELLA = "La Estrella"
    LAS_CABRAS = "Las Cabras"
    LITUECHE = "Litueche"
    LOLOL = "Lolol"
    MACHALI = "Machalí"
    MALLOA = "Malloa"
    MARCHIHUE = "Marchihue"
    NANCAGUA = "Nancagua"
    NAVIDAD = "Navidad"
    OLIVAR = "Olivar"
    PALMILLA = "Palmilla"
    PAREDONES = "Paredones"
    PERALILLO = "Peralillo"
    PEUMO = "Peumo"
    PICHIDEGUA = "Pichidegua"
    PICHILEMU = "Pichilemu"
    PLACILLA = "Placilla"
    PUMANQUE = "Pumanque"
    QUINTA_DE_TILCOCO = "Quinta de Tilcoco"
    RANCAGUA = "Rancagua"
    RENGO = "Rengo"
    REQUINOA = "Requínoa"
    SAN_FERNANDO = "San Fernando"
    SAN_FRANCISCO_DE_MOSTAZAL = "San Francisco de Mostazal"
    SAN_VICENTE_DE_TAGUA_TAGUA = "San Vicente de Tagua Tagua"
    SANTA_CRUZ = "Santa Cruz"
    CAUQUENES = "Cauquenes"
    CHANCO = "Chanco"
    COLBUN = "Colbún"
    CONSTITUCION = "Constitución"
    CUREPTO = "Curepto"
    CURICO = "Curicó"
    EMPEDRADO = "Empedrado"
    HUALANE = "Hualañé"
    LICANTEN = "Licantén"
    LINARES = "Linares"
    LONGAVI = "Longaví"
    MAULE = "Maule"
    MOLINA = "Molina"
    PARRAL = "Parral"
    PELARCO = "Pelarco"
    PELLUHUE = "Pelluhue"
    PENCAHUE = "Pencahue"
    RAUCO = "Rauco"
    RETIRO = "Retiro"
    ROMERAL = "Romeral"
    RIO_CLARO = "Río Claro"
    SAGRADA_FAMILIA = "Sagrada Familia"
    SAN_CLEMENTE = "San Clemente"
    SAN_JAVIER_DE_LONCOMILLA = "San Javier de Loncomilla"
    SAN_RAFAEL = "San Rafael"
    TALCA = "Talca"
    TENO = "Teno"
    VICHUQUEN = "Vichuquén"
    VILLA_ALEGRE = "Villa Alegre"
    YERBAS_BUENAS = "Yerbas Buenas"
    BULNES = "Bulnes"
    CHILLAN_VIEJO = "Chillán Viejo"
    CHILLAN = "Chillán"
    COBQUECURA = "Cobquecura"
    COELEMU = "Coelemu"
    COIHUECO = "Coihueco"
    EL_CARMEN = "El Carmen"
    NINHUE = "Ninhue"
    NIQUEN = "Ñiquén"
    PEMUCO = "Pemuco"
    PINTO = "Pinto"
    PORTEZUELO = "Portezuelo"
    QUILLON = "Quillón"
    QUIRIHUE = "Quirihue"
    RANQUIL = "Ránquil"
    SAN_CARLOS = "San Carlos"
    SAN_FABIAN = "San Fabián"
    SAN_IGNACIO = "San Ignacio"
    SAN_NICOLAS = "San Nicolás"
    TREGUACO = "Treguaco"
    YUNGAY = "Yungay"
    ALTO_BIOBIO = "Alto Biobío"
    ANTUCO = "Antuco"
    ARAUCO = "Arauco"
    CABRERO = "Cabrero"
    CANETE = "Cañete"
    CHIGUAYANTE = "Chiguayante"
    CONCEPCION = "Concepción"
    CONTULMO = "Contulmo"
    CORONEL = "Coronel"
    CURANILAHUE = "Curanilahue"
    FLORIDA = "Florida"
    HUALPEN = "Hualpén"
    HUALQUI = "Hualqui"
    LAJA = "Laja"
    LEBU = "Lebu"
    LOS_ALAMOS = "Los Álamos"
    LOS_ANGELES = "Los Ángeles"
    LOTA = "Lota"
    MULCHEN = "Mulchén"
    NACIMIENTO = "Nacimiento"
    NEGRETE = "Negrete"
    PENCO = "Penco"
    QUILACO = "Quilaco"
    QUILLECO = "Quilleco"
    SAN_PEDRO_DE_LA_PAZ = "San Pedro de la Paz"
    SAN_ROSENDO = "San Rosendo"
    SANTA_BARBARA = "Santa Bárbara"
    SANTA_JUANA = "Santa Juana"
    TALCAHUANO = "Talcahuano"
    TIRUA = "Tirúa"
    TOME = "Tomé"
    TUCAPEL = "Tucapel"
    YUMBEL = "Yumbel"
    ANGOL = "Angol"
    CARAHUE = "Carahue"
    CHOLCHOL = "Cholchol"
    COLLIPULLI = "Collipulli"
    CUNCO = "Cunco"
    CURACAUTIN = "Curacautín"
    CURARREHUE = "Curarrehue"
    ERCILLA = "Ercilla"
    FREIRE = "Freire"
    GALVARINO = "Galvarino"
    GORBEA = "Gorbea"
    LAUTARO = "Lautaro"
    LONCOCHE = "Loncoche"
    LONQUIMAY = "Lonquimay"
    LOS_SAUCES = "Los Sauces"
    LUMACO = "Lumaco"
    MELIPEUCO = "Melipeuco"
    NUEVA_IMPERIAL = "Nueva Imperial"
    PADRE_LAS_CASAS = "Padre las Casas"
    PERQUENCO = "Perquenco"
    PITRUFQUEN = "Pitrufquén"
    PUCON = "Pucón"
    PUREN = "Purén"
    RENAICO = "Renaico"
    SAAVEDRA = "Saavedra"
    TEMUCO = "Temuco"
    TEODORO_SCHMIDT = "Teodoro Schmidt"
    TOLTEN = "Toltén"
    TRAIGUEN = "Traiguén"
    VICTORIA = "Victoria"
    VILCUN = "Vilcún"
    VILLARRICA = "Villarrica"
    CORRAL = "Corral"
    FUTRONO = "Futrono"
    LA_UNION = "La Unión"
    LAGO_RANCO = "Lago Ranco"
    LANCO = "Lanco"
    LOS_LAGOS = "Los Lagos"
    MARIQUINA = "Mariquina"
    MAFIL = "Máfil"
    PAILLACO = "Paillaco"
    PANGUIPULLI = "Panguipulli"
    RIO_BUENO = "Río Bueno"
    VALDIVIA = "Valdivia"
    ANCUD = "Ancud"
    CALBUCO = "Calbuco"
    CASTRO = "Castro"
    CHAITEN = "Chaitén"
    CHONCHI = "Chonchi"
    COCHAMO = "Cochamó"
    CURACO_DE_VELEZ = "Curaco de Vélez"
    DALCAHUE = "Dalcahue"
    FRESIA = "Fresia"
    FRUTILLAR = "Frutillar"
    FUTALEUFU = "Futaleufú"
    HUALAIHUE = "Hualaihué"
    LLANQUIHUE = "Llanquihue"
    LOS_MUERMOS = "Los Muermos"
    MAULLIN = "Maullín"
    OSORNO = "Osorno"
    PALENA = "Palena"
    PUERTO_MONTT = "Puerto Montt"
    PUERTO_OCTAY = "Puerto Octay"
    PUERTO_VARAS = "Puerto Varas"
    PUQUELDON = "Puqueldón"
    PURRANQUE = "Purranque"
    PUYEHUE = "Puyehue"
    QUEILEN = "Queilén"
    QUELLON = "Quellón"
    QUEMCHI = "Quemchi"
    QUINCHAO = "Quinchao"
    RIO_NEGRO = "Río Negro"
    SAN_JUAN_DE_LA_COSTA = "San Juan de la Costa"
    SAN_PABLO = "San Pablo"
    AISEN = "Aisén"
    CHILE_CHICO = "Chile Chico"
    CISNES = "Cisnes"
    COCHRANE = "Cochrane"
    COIHAIQUE = "Coihaique"
    GUAITECAS = "Guaitecas"
    LAGO_VERDE = "Lago Verde"
    OHIGGINS = "O'Higgins"
    RIO_IBANEZ = "Río Ibáñez"
    TORTEL = "Tortel"
    ANTARTICA = "Antártica"
    CABO_DE_HORNOS = "Cabo de Hornos (Ex Navarino)"
    LAGUNA_BLANCA = "Laguna Blanca"
    NATALES = "Natales"
    PORVENIR = "Porvenir"
    PRIMAVERA = "Primavera"
    PUNTA_ARENAS = "Punta Arenas"
    RIO_VERDE = "Río Verde"
    SAN_GREGORIO = "San Gregorio"
    TIMAUKEL = "Timaukel"
    TORRES_DEL_PAINE = "Torres del Paine"
